"""Moved example from word into details

Revision ID: 55a9af9a0acd
Revises: 7560a2eb2af6
Create Date: 2025-01-16 20:16:07.746584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a9af9a0acd'
down_revision = '7560a2eb2af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derivatives',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'word')
    )
    op.create_table('details',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('synonyms', sa.String(length=100), nullable=True),
    sa.Column('meaning', sa.String(length=100), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'synonyms')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details')
    op.drop_table('derivatives')
    op.drop_table('words')
    op.drop_table('days')
    # ### end Alembic commands ###
