"""empty message

Revision ID: 7560a2eb2af6
Revises: 
Create Date: 2025-01-07 16:00:18.091007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7560a2eb2af6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('days')
    op.drop_table('derivatives')
    op.drop_table('details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pos', sa.VARCHAR(length=10), nullable=False),
    sa.Column('synonyms', sa.VARCHAR(length=200), nullable=True),
    sa.Column('meaning', sa.VARCHAR(length=200), nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derivatives',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pos', sa.VARCHAR(length=10), nullable=True),
    sa.Column('word', sa.VARCHAR(length=50), nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('days',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), nullable=False),
    sa.Column('example', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['day'], ['days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
